### ISSUE TITLE
Tell me the best book Quote ..?

### ISSUE THREAD

**Issue by yaraayman** [anasmahmouud/T17Sprint0C2#4]
Author: Yara Ayman 
project: collects best quotes written in books 
milestone: acts as a container for the issues 
Assignee: Anas Mahmoud,Ahmed Yasser,Ahmed Ehab,Ahmed Amr
  Would you guys get me the best quote you ever read in a book?

**Comment by ahmedattia213** [comment]
The goal isn’t to live forever, the goal is to create something that will.
– Chuck Palahniuk, Diary

**Comment by anasmahmouud** [comment]
“A room without books is like a body without a soul.” 
― Marcus Tullius Cicero

**Comment by ahmadehab-97** [comment]
"Falling down is how we grow, staying down is how we die."
-Brian Vaszely
